-- Altera_Elastic_Fifo.vhd

-- Generated using ACDS version 17.1 590

library IEEE;
library Altera_Elastic_Fifo_fifo_171;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use Altera_Elastic_Fifo_fifo_171.Altera_Elastic_Fifo_pkg.all;

entity Altera_Elastic_Fifo is
	port (
		data  : in  std_logic_vector(257 downto 0) := (others => '0'); --  fifo_input.datain
		wrreq : in  std_logic                      := '0';             --            .wrreq
		rdreq : in  std_logic                      := '0';             --            .rdreq
		clock : in  std_logic                      := '0';             --            .clk
		sclr  : in  std_logic                      := '0';             --            .sclr
		q     : out std_logic_vector(257 downto 0);                    -- fifo_output.dataout
		usedw : out std_logic_vector(4 downto 0);                      --            .usedw
		full  : out std_logic;                                         --            .full
		empty : out std_logic                                          --            .empty
	);
end entity Altera_Elastic_Fifo;

architecture rtl of Altera_Elastic_Fifo is
begin

	fifo_0 : component Altera_Elastic_Fifo_fifo_171.Altera_Elastic_Fifo_pkg.Altera_Elastic_Fifo_fifo_171_fjuzqtq
		port map (
			data  => data,  --  fifo_input.datain
			wrreq => wrreq, --            .wrreq
			rdreq => rdreq, --            .rdreq
			clock => clock, --            .clk
			sclr  => sclr,  --            .sclr
			q     => q,     -- fifo_output.dataout
			usedw => usedw, --            .usedw
			full  => full,  --            .full
			empty => empty  --            .empty
		);

end architecture rtl; -- of Altera_Elastic_Fifo
